#!/bin/bash

algorithm=$1
inputFile=$2
outputFile=$3

if [ $algorithm = $"bubblesort" ]; then
	python sort/bubble_sort.py $inputFile $outputFile
elif [ $algorithm = $"shellsort" ]; then
	python sort/shell_sort.py $inputFile $outputFile
elif [ $algorithm = $"mergesort" ]; then
	python sort/merge_sort.py $inputFile $outputFile
elif [ $algorithm = $"quicksort" ]; then
	python sort/quick_sort.py $inputFile $outputFile
fi
