#!/bin/bash

algorithm=$1
replications=$2
inputFile=$3
outputFile=$4


for (( i=1; i<=$replications; i++ )) ;
    do
        python sort_controller/$algorithm'.py' $replications $inputFile $outputFile
    done 

