#!/bin/bash

algorithm=$1
inputFile=$2
outputFile=$3

if [ $algorithm = "Bubblesort" ]; then
	python3 sort/bubble_sort.py
elif [ $algorithm = $"Shellsort" ]; then
	python3 sort/shell_sort.py
elif [ $algorithm = "Mergesort" ]; then
	python3 sort/merge_sort.py
elif [ $algorithm = "Quicksort" ]; then
	python3 sort/quick_sort.py
fi